cozy/cozy-client-js

- src/index.js
To not run init if no options are passed to the constructor.
This fixes the init of the global instance `window.cozy` on browsers.
> Fix options passing on constructor

- src/index.js
I believe there is no reason to prevent initialization if `cozy-client` has already been initialized.
For example, if a user errs in the cozy server's url, `cozy-client` attemps to initialize, receives HTTP errors that are displayed to the user who has the opportunity to change the url. Then `cozy-client` must be reset/re-initialized.
> call init to re-init

- docs/README.md
- src/files.js
- src/index.js
- src/jsonapi.js
- test/integration/files.js
- test/unit/jsonapi.js
Add a function to generate a download link for 1 or more files.
We keep the old download in parallel as it might be useful for other use-cases.
> Add 2 steps download

- docs/README.md
- test/unit/files.js
It already works thanks to node-fetch.
Add some assertions in unit test to make sure body remains
the same upstream, and update documentation accordingly.
> Make node stream support official in cozy.files.downloadBy*()

- src/auth_v3.js
- test/unit/auth.js
I don't know why there were an exception thrown if we create a client without `redirectURI`, `softwareID` or `clientName`.
It does not really help when we want to `getClient()`.
But it may be mandatory for `cozy.init()` with oauth, does not it?
> fix: getClient needs only clientID and registrationAccessToken

- src/index.js
- test/integration/crud.js
- test/integration/files.js
- test/integration/mango.js
- test/integration/offline.js
- test/integration/relations.js
- test/integration/settings.js
- test/unit/auth.js
- test/unit/crud.js
- test/unit/files.js
- test/unit/mango.js
- test/unit/offline.js
- test/unit/settings.js
- webpack.config.js
This PR ensure we build a real UMD module, and exposes it at root level under the namespace `cozy` (i.e. `window.cozy.client`)
> Build UMD modules in root['cozy']

- docs/README.md
When reading the documentation, I asked myself what is the default value for `disablePromises`, so I guess it worth to be added.
> [docs] add default value

- docs/README.md
- src/files.js
- test/mock-api.js
- test/unit/files.js
- Make `lastModifiedDate` option of `updateById()` official
(only updated tests and doc since it already worked)
- Add `checksum` option to `create()` and `updateById()`
- Add `ifMatch` option to `updateById()` and `updateAttributesBy*()`
- Fixed `path` parameter typo in `updateAttributesById()` doc
Needs https://github.com/cozy/cozy-stack/pull/305
> Add some missing cozy.files.*() options

- docs/README.md
As promised, this PR updates the whole documentation to reflect the new namespace under which `cozy-client-js` is published 😅
> [chore] Updated namespace in docs

- docs/README.md
- src/files.js
- src/index.js
- test/unit/files.js
To call `cozy.files.getDownloadLink`, I needed to generate path for a given file.
As this little piece of logic is already used in Files, I think we should add a little helper in cozy-client-js to facilitates further developments and mutualize code.
> [feat] Add helper to get file path

- src/offline.js
I need to do something like this for https://github.com/cozy/cozy-files-v3/pull/138
Maybe, instead of adding an `onError` onto the replication, we could provide a way to handling an `onError` custom code within the whole cozy-client-js code base. We could set it up in the `init()` function.
You decide.
> handling custom code on replication complete or error

- src/files.js
- src/offline.js
- test/integration/offline.js
onError and onComplete are both being called too early.
And I don't believe it is a good idea to raise a *no database error* if we start a replication.
I do believe that when we launch a replication, if there is no local database, we should create one.
It is related to https://github.com/cozy/cozy-files-v3/pull/157
> feat: enhance offline behavior

- src/fetch.js
- src/offline.js
Here is the workflow when repeated replication are engaged:
1. open the application
1. call `statById` to list the default folder's content
(via `openFolder`)
1. `startRepeatedReplication` (via `registerDevice`)
Then the token becomes obsolete and need to be refreshed.
If a request is sent to the server, it uses this code to refresh the
token. But it get a response with code `400`.
See https://github.com/cozy/cozy-client-js/blob/master/src/fetch.js#L35
On the other hand, the repeated replication continues to work until
we refresh the page, I can't understand why.
See https://github.com/cozy/cozy-client-js/blob/master/src/offline.js#L115
> feat: refresh token for offline replication

- src/files.js
When a cordova application uses the cordova-plugin-file plugin, `window.File` is overwritten by another object, see https://github.com/apache/cordova-plugin-file/blob/master/www/File.js#L31.
So the line `data instanceof File` is `false` then the code enters the `isBlob` conditionnal scope that is why we change this line to get `data.type` if it exists or `contentTypeOctetStream` otherwise.
> fix: mime-type was not detected in cordova

- test/integration/files.js
I take this opportunity to ask if this very test is really interesting.
I think it test pouchDB and not very much the library's code.
If we want to be sure the replication works, we only have to check
if the `offline` document exists (`!== undefined`), don't we?
> test: update tests with built-in functions

- package.json
I suggest `yarn watch` build a non-minified
version of the lib as the `yarn watch` on
others projects use the non-minified version.
Here is my workflow:
```
z cozy-client-js
yarn link
yarn watch &
z cozy-files-v3
yarn link cozy-client-js
yarn watch:mobile:standalone &
```
*With z to jump to a folder.*
> chore: watch mode build :construction_worker:

- package.json
- src/index.js
- src/intents.js
- test/unit/intents.js
- yarn.lock
This PR adds `cozy.client.intents.start()` methods wich allow to inject an iframe from another service for a given intent.
`cozy.client.intents.resolve()`, used in services, will be implemented later.
At this time, it is almost a POC. As we don't have a service to get the proper url from a given intent, the `cozy.client.intents.start()` method takes a temporary third argument, which is the mocked url that we want to use for the intent.
It has been discussed with @y-lohse where we should implement the intents logic.
First, it as been proposed that they may be served by the cozy-bar. But as intents are needed both in onboarding and in intent service pages, which do not contain a cozy-bar, we decided to implement them in cozy-client-js. Our fear was that DOM interaction would have been too …
> feat: Add intents

- docs/offline.md
- src/offline.js
- test/integration/offline.js
- test/unit/offline.js
Should fix the issue discussed in https://github.com/cozy/cozy-client-js/issues/88.
Instead of editing [`webpack.target.mobile.js`](https://github.com/cozy/cozy-files-v3/blob/master/config/webpack.target.mobile.js) like @m4dz proposal, I suggest to use `webpack.ProvidePlugin()` instead (Actually using  `imports-loader` did not work for me) :
```js
module.exports = {
...
plugins: [
new webpack.ProvidePlugin({
'PouchDB': 'pouchdb',
'pouchdbFind': 'pouchdb-find'
})
]
}
```
> chore: removes PouchDB dependency

- docs/README.md
- src/index.js
This feature add cozyVersion parameter.
The purpose is to delete [the request to the server '/status/'](https://github.com/cozy/cozy-client-js/blob/88a63b5b052fbe78e9e1835dc4dd61d1ab8c6504/src/index.js#L238) for the offline mode.
> feat: Add cozyVersion parameter to remove '/status/' request (offline) :bath:

- src/fetch.js
When fetch returns a 400 but client is not revoked, the client was starting an infinite loop of tries/failures
> Break an infinite loop of retry/failure 

- CHANGELOG.md
- src/intents.js
- test/unit/intents.js
Interesting case in onboarding, with four services, all able of starting an intent. When one of the intents was not properly ended or cancelled (when the modal is closed by clicking on its overlay for example), the listener over postMessage events was still listening for `intent:ready` message and still responding with its given data (here: the konnector slug).
Consquence : if an intent to EDF konnector was open and "closed" by a click on modal overlay, all future intents were invariably serving the EDF konnector, because of the old listerner always present.
To solve this issue, my first thought was to listen the iframe itself and remove the listener when it was removed from DOM, but security/permission issues occured. So I made two things :
* The service part now listen for the `unload` …
> feat: stronger postMessage handling in intents

- src/files.js
- src/index.js
- test/integration/files.js
When developing https://github.com/cozy/cozy-photos-v3/pull/77 I realized that we miss some permissions to access everything needed.
> fix: not enough perm to share collections

- CHANGELOG.md
- docs/files-api.md
- src/fetch.js
- src/index.js
- src/mango.js
- src/relations.js
`cozy.client.data.fetchReferencedFiles(doc)` fetches the files bound to the document.
(see cozy-stack [documentation](https://cozy.github.io/cozy-stack/references-docs-in-vfs.html) for more details).
It returns a promise for a list of files.
`cozy.client.files.query(indexReference, query)` find files using an index.
It returns a promise with a list of files matching the query. Results will be returned in the order defined for the index.
- `query` is an object with the following fields:
* `selector`: a mango selector
* `limit`: maximum number of results
* `skip`: ignore the first x results (pagination)
* `wholeResponse`: when set to true, the whole query response will be returned instead of just the docs. This is useful when paginating, because you'll get the `next` property in the …
> Add cozy.client.files.query and fetchReferencedFiles

- docs/intents-api.md
- src/intents.js
- test/unit/intents.js
The service can make a call to service to set the size of its modale : 
```javascript
cozy.client.intents.createService(intent, window)
.then(service => {
service.setSize({width: '400px', height: '400px'})
})
```
The service is responsible to make the modale displayable on screen in different possible resolutions (mobile, desktop). The client application requesting the intent is still responsible for the display of the modal and the default size of it, if the service does not request any special modale size.
> feat: make possible for the service to specify the size of the intent modale

- CHANGELOG.md
- docs/intents-api.md
- src/intents.js
- test/unit/intents.js
Two main points:
* Handle `exposeIntentFrameRemoval` data flag to terminate the service without removing the intent DOM node directly but by providing the removal function to the client
__Example of usage__: Claudy has an animated (CSS) menu closing. Using this feature it will be possible to terminate the intent `.then` listen the animation ending before removing the intent iframe node using the resolved `removeIntentFrame ` function (and avoiding a sudden blank view in the Claudy view)
* Add an `onReadyCallback` optional argument to the `create` method in order to allow providing a callback function to be run when the intent iframe will be loaded (iframe `onload` listener).
__Example of usage__: Claudy will now wait the intent iframe to be totally loaded before beginning its opening …
> Intents improvements (onReadyCallback, exposeFrameRemoval)

- src/auth_v3.js
- src/index.js
We have a case where the `scope` that is being requested might be different from the one that is cached, but the oauth flow always use the cached version, so the new scope is never picked up.
I've added a flag to the `client.authorize()` method that explicitly tells the oauth flow to ignore the cache. It defaults to false so existing calls shouldn't be affected. Does that make sense? Is there a better way to accomplish this?
> feat: option to allow bypassing credentials cache

- src/index.js
- src/relations.js
I also removed the annoying console.warn when using cozy.fetchJSON.
> feat: Use sort=datetime when fetching referenced files

- src/index.js
- src/jobs.js
- test/integration/data.js
- test/integration/jobs.js
- test/testapp-manifest.json
The `/jobs/queue` API has been changed in the stack to actually return the jobs data. This PR adapt `cozy-client-js` to this change.
> Adapt jobs.count and add queued method

- docs/offline.md
The production build of Bank was broken because of this.
In prod, since `cozy-client-js` is injected by the stack, it has not been processed by `wepback` and the `ProvidePlugin`. Thus you need to bind `PouchDB` to `window`.
> doc: PouchDB needs to be attached to window in production

- package.json
- src/offline.js
- webpack.config.js
- yarn.lock
When it comes to offline support, we are in the process of changing how we handle things. Until recently, only cozy-drive mobile was using the offline part of cozy-client-js. Now, cozy-bank uses it too, cozy-drive uses it in it's web version as well, and the trend is likely to continue.
The offline module requires `pouchdb`. So far, we provided it through a webpack plugin (see #88), but this a) not practical when many apps need it and b) doesn't work when the stack serves `cozy-client-js`(we don't get the chance to provide anything).
This PR adds `pouchdb` as a regular dependency. The distributed file size almost doubles, from 120kb to ~300kb (both minified). It sucks, but I think this makes the most sense.
> chore: add pouch as a dependency

- package.json
- src/offline.js
- yarn.lock
Offers the option ot use the `sqlite` adapter with pouch. Unfortunately, there is a problem with the current release of the adapter, so I've pinned the dependency on a commit that contains a fix for it but has not been merged yet. See here : https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/pull/79
> feat: provide SqlLitePlugin for mobile

- src/fetch.js
If a response from stack has a `data` attribute, `handleJSONResponse` will return directly the content of data (see https://github.com/cozy/cozy-client-js/blob/master/src/jsonapi.js#L41).
In https://github.com/cozy/cozy-collect/pull/343, for retrieving jobs with new route https://github.com/cozy/cozy-stack/blob/master/docs/jobs.md#get-jobstriggersjobs, we need to be able to get the full raw response and not only the content of the `data` attribute.
This PR allow to pass a new `processJSONAPI` option to fetchJSON to bypass the default behavior and get the full raw response.
> feat: allow to specify processJSONAPI in fetchJSON options ✨

- CHANGELOG.md
- src/files.js
Having a trailing space in a Transifex translation, we ended up with a space in our file name, which was causing an error on Windows.
> feat: sanitize file name 🚑

- CHANGELOG.md
- package.json
- `babel-polyfill` is no more included https://github.com/cozy/cozy-client-js/commit/b12fb52da002742c83bfc87632a3bc6440d1a8c0
> release 0.4.3

- src/files.js
Turns out, file names can be uppercase too. Who knew?
> fix: case insentisitve mime type detection

- src/fetch.js
- src/index.js
There are weird situations where the app's cookie doesn't match the actual session cookie. When that happens, all XHR calls will fail until the cookie is fixed. The proper way to fix the cookie is to reload the page with a `?disconnect=1` parameter.
I've done this, but since the change is at such a low level, this will impact every app that uses cozy-client-js. Which is probably what we want.
The redirection only happens if we're actually on an app page in a browser. So if you're in node.js, or on `file://whatever` in a cordova or electron app, this change shouldn't affect you at all.
If, for some reason, you don't want the page reload, or want to handle the error yourself, you can supply a new option to `cozy.client.init`. `onInvalidTokenError` can be a function, or it can be …
> fix: BREAKING CHANGE detect expired token and reload page

- src/intents.js
- test/unit/intents.js
If an application wants a specific service for its intent,
it can specify `filterServices` in the option when creating
the intent.
> Ability to filter services returned by the stack

- docs/intents-api.md
- src/index.js
- src/intents.js
- test/mock-api.js
- test/unit/intents.js
~PRIORITY : VERY LOW~
This PR tries to solve the redirection point exposed in #201 and adds two methods to intents API, both used to easily redirect to a given document or a given doctype. The two added methods are:
* `getRedirectionURL(type, data)` which retrieves a redirection URL.
* `redirect(type, data)` which retrieves a redirection URL and performs the redirection.
```jsx
import Button from 'cozy-ui/react/Button'
// [...]
render() {
const { folder } = this.props
return (
<Button
label={`Open ${folder.name}`}
onClick={() => cozy.client.intents.redirect('io.cozy.files', folder)}
/>
)
}
```
Redirection are declared in `manfiest.webapp`, like a regular intent
```json
"intents": [
{
"action": "REDIRECT",
"type": [
"io.cozy.konnectors"
],
"href": "/"
}
],
```
* For now, it is still not …
> feat: add intents.redirect() method ✨

- src/intents.js
- test/unit/intents.js
First errors in `intents.createService()` were throwing error synchronously. To be catch by `.catch()` method, they must be thrown with a Promise rejection.
> feat: asynchronous errors in intents.createService() ✨

- package.json
- yarn.lock
`isomorphic-fetch` is an actual dependency for node, so it can't be in `devDependency` or it won't get installed.
> chore: declare iso fetch as dependency

- docs/intro.md
`scopes` was outside of `clientParams`, it should be inside.
See tests : https://github.com/cozy/cozy-client-js/blob/b0fd96f7c8c545dd0b6df610b839e752435471e0/test/integration/auth.js#L21-L32
Thanks to Schoumi for spotting the error !
> fix: scopes is in clientParams

- src/intents/index.js
This adds a `redirectFn` so we can pass a custom redirection function when we call `cozy.client.intents.redirect`.
This enables us to use an inapp browser and redirect the user using intents redirect on mobile apps, for example.
> feat(intents): add an redirectFn parameter to redirect method

- src/intents/index.js
- test/mock-api.js
- test/unit/intents.js
The hash part is now provided at the end of the `href` by the stack, ccjs was skipping it then. Now it's handled properly.
> Properly compute intents base URL with hash

- src/index.js
It is now convenient to expose this method to fetch icons from stack.
Used in applications which did not switch to cozy-client yet.
> Expose fetch method

- package.json
- yarn.lock
https://github.com/cozy/cozy-client-js/network/alert/yarn.lock/growl/open
> chore: upgrade libs to stop growl security alert

- docs/files-api.md
- src/relations.js
The recommended way to paginate view results in [CouchDB](https://docs.couchdb.org/en/stable/ddocs/views/pagination.html#paging-alternate-method), and therefore the stack, is through [cursors](https://docs.cozy.io/en/cozy-stack/jsonapi/#pagination).
This is because `skip` performs badly on large data collections, as it requires to scan the full B-Tree. 
For instance, a query on 2500 documents, with a limit of 100 docs per request, was taking more than 25s overall, with sometimes more than 1s per paginated request.
In `fetchReferencedFiles`, the sort was forced on `datetime`, which, behind the hoods, triggers the use of the `referenced-by-sorted-by-datetime` view (see [here](https://github.com/cozy/cozy-stack/blob/4e8da5cc1e5401ea43029de6d90bf248fac82405/web/files/references.go#L77-L81 ) …
> Add the possibility to use cursor-based pagination for references

- docs/files-api.md
- src/files.js
It is useful for the cozy-desktop client as we want to have exactly the
same filenames on the client and on the cozy instance.
This is an up-to-date version of https://github.com/cozy/cozy-client-js/pull/281
>  Merge pull request #290 from cozy-client-js/no-sanitize-filename-option

- package.json
- yarn.lock
js-yaml is upgraded to 3.13.1 as recommended by github
> fix: upgrade js-yaml to avoir security alert

- docs/files-api.md
- src/files.js
sourceAccount is the io.cozy.accounts account id associated to the connector which uploaded the file
sourceAccountIdentifier is the user identifier (login most of the time) associated to the account
> feat: allow to add sourceAccount and sourceAccountIdentifer in cozyMetadata while uploading a file

- .travis.yml
`cozy-stack` has switched to go modules which requires us to use the
`GO111MODULE=on` env variable when running `go get` to fetch and build
`cozy-stack`.
Besides, `cozy-stack` has a dependency to `github.com/robfig/cron/v3`
which is not completely compatible with go modules (i.e. the `v3`
part) and prevents us from running `go get -u`.
> fix: Use go modules to fetch and build cozy-stack

- src/offline.js
- webpack.config.js
Cozy Desktop uses `cozy-client-js` to interact with the user's Cozy
and needs to be able to operate behind a proxy as well as define a
custom User-Agent per user so support can follow their requests on the
server.
Electron offers better support for proxy configuration than Node so
Cozy Desktop uses `electron-fetch` instead of `isomorphic-fetch` and
`electron-proxy-agent` to customize the request's Agent with the proxy
configuration.
This means that Cozy Desktop needs to be able to replace the `fetch`
method called by `cozy-client-js` as well so all requests made to the
server use this custom configuration.
The webpack's `providePlugin` plugin creates a closure with the given
module around all modules calling the specified method. In our case,
every module of `cozy-client-js` calling …
> fix: Use global fetch instead of closure

- README.md
- docs/deprecated.md
- docs/toc.yml
You want that cozy-client-js not being indexed
in our official documentation since is a bit
confusing for our users.
If really needed, the user can still access
to the doc on github
> docs: Add a deprecated notice in the TOC

- src/files.js
We can pass the `Executable` query-string parameter when uploading a
new file but `cozy-client-js` does not send it when uploading a new
version although `cozy-stack` accepts it.
Clients like `cozy-desktop` should be able to pass this parameter
along to keep it in sync with their local metadata.
> feat: Send Executable with file update

- .travis.yml
Travis does not allow binding IPv6 addresses on their Full VM images
which is the only option for `amd64` architectures.
Since we don't really care about having an IPv6 bound server for our
builds, we can force the hosts to an IPv4 address.
> ci: Bind server to IPv4 address only
