cozy/cozy-client-js

- .travis.yml
- CONTRIBUTING.md
- README.md
- docs/api-cheatsheet.md
- docs/architecture.md
- docs/browser-sdk-transition.md
- package.json
- test/package.json
- webpack.config.js
**Warning** We should rename the repository at the same time we merge this PR
> Rename this package to cozy-client-js

- README.md
- docs/api-cheatsheet.md
- docs/browser-sdk-transition.md
- package.json
- src/crud.js
- src/index.js
- src/mango.js
- src/utils.js
- test/integration/crud.js
- test/integration/mango.js
- test/mock-api.js
- test/mock-iframe-token.js
- test/unit/mango.js
- test/unit/mango_utils.js
This still needs more tests around edge cases, but opening a PR for @jinroh to review.
> Mango and misc

- docs/README.md
- docs/planned.md
- src/files.js
- src/index.js
- src/utils.js
- test/integration/files.js
- test/mock-api.js
- test/unit/files.js
Add a `createFile`, `updateFile`, `createDirectory` and a `trash` function. ~~To merge after #14.~~
> createFile, updateFile, createDirectory and trash

- CONTRIBUTING.md
- README.md
- docs/README.md
- src/files.js
- src/index.js
- src/utils.js
- test/integration/files.js
- test/mock-api.js
- test/unit/files.js
This PR add a method `updateAttributes` to update files or directories attributes by id or path.
> Add updateAttributes

- docs/planned.md
- src/files.js
- src/index.js
- src/jsonapi.js
- test/helpers.js
- test/integration/files.js
- test/mock-api.js
- test/unit/files.js
- test/unit/jsonapi.js
**Note** JSONAPI unpacking is good enough for usage but it would really benefit when used with a JS Data Framework (like https://github.com/dixieio/redux-json-api)
> Files & Folders stat

- .travis.yml
The stack v3 must be started before adding the dev instance
> FIx travis build

- docs/README.md
- src/auth_v3.js
- src/index.js
- test/mock-api.js
- test/unit/auth.js
> Add update & register client functions for devices

- .npmignore
```
$ ls -al
total 448
drwxr-xr-x   19 kosssi  staff     646  1 fév 09:09 .
drwxr-xr-x  179 kosssi  staff    6086  1 fév 09:09 ..
-rw-r--r--    1 kosssi  staff     114 31 jan 17:59 .babelrc
-rw-r--r--    1 kosssi  staff     702 31 jan 17:59 .npmignore
-rw-r--r--    1 kosssi  staff    2049 31 jan 17:59 .travis.yml
-rw-r--r--    1 kosssi  staff    6062 31 jan 17:59 CONTRIBUTING.md
-rw-r--r--    1 kosssi  staff    1074 31 jan 17:59 LICENSE
-rw-r--r--    1 kosssi  staff    3961 31 jan 17:59 README.md
drwxr-xr-x    3 kosssi  staff     102 31 jan 17:59 _workspace
drwxr-xr-x    6 kosssi  staff     204  1 fév 09:09 dist
drwxr-xr-x    7 kosssi  staff     238  1 fév 09:09 docs
-rw-r--r--    1 kosssi  staff     352 31 jan 17:59 index.html
-rw-r--r--    1 kosssi  staff     235 31 jan 17:59 …
```
> Add .npmignore to reduce weight :nut_and_bolt:

- .travis.yml
- docs/README.md
- src/auth_v2.js
- src/auth_v3.js
- src/fetch.js
- src/index.js
- src/settings.js
- test/integration/crud.js
- test/integration/files.js
- test/integration/mango.js
- test/integration/offline.js
- test/integration/settings.js
- test/mock-api.js
- test/testapp-git-daemon.sh
- test/testapp-manifest.json
- test/unit/auth.js
- test/unit/crud.js
- test/unit/files.js
- test/unit/mango.js
- test/unit/offline.js
- test/unit/settings.js
This PR adds the handling of applications tokens for permissions and adds a diskUsage API using these permissions.
The installed application to generate the token from is https://github.com/jinroh/cozy-mini which has permissions on `io.cozy.settings`.
> Permissions and disk usage

- docs/README.md
- src/files.js
- test/integration/files.js
- test/unit/files.js
See: https://github.com/cozy/cozy-stack/pull/288
> Add a lastModifiedDate option to directory creation

- docs/README.md
- src/files.js
- test/integration/files.js
- test/unit/files.js
Please note this PR will probably conflict with https://github.com/cozy/cozy-client-js/pull/65
Once one is merged, I can rebase the other.
The integration test may not be so useful (2nd commit), so I can eventually remove it.
> Node streams

- src/files.js
- test/integration/files.js
- test/unit/files.js
> Fix creation date

- src/files.js
> Do not import stream module to check file data type in production

- src/index.js
- test/integration/data.js
- test/integration/files.js
- test/integration/mango.js
- test/integration/offline.js
- test/integration/relations.js
- test/integration/settings.js
- test/unit/auth.js
- test/unit/data.js
- test/unit/files.js
- test/unit/mango.js
- test/unit/offline.js
- test/unit/settings.js
- webpack.config.js
> Build UMD modules in root['cozy']

- docs/README.md
Code and documentation were not up-to-date.
> docs: update examples

- docs/README.md
- src/index.js
- src/settings.js
- test/mock-api.js
- test/unit/settings.js
This PR adds more methods to the settings namespace.
> [feat] Support more settings API methods

- CONTRIBUTING.md
- README.md
I had hard time to run integration tests on my local environment.
But as it is very useful, you may find the workflow I use.
If it can interest and help anyone, be my guess.
> readme: how to run integration tests on local environment

- CONTRIBUTING.md
Sometimes, when you let days pass, you realize that it may be finally better like that.
Nothing change in the content, I just moved the paragraph to a more appropriate chapter.
What do you think?
> Move paragraph to appropriate chapter

- src/index.js
- src/offline.js
It is used in https://github.com/cozy/cozy-files-v3/pull/138
> feat: add API to destroy all databases

- src/index.js
- src/offline.js
- test/integration/offline.js
- test/unit/offline.js
> Refactoring offline.js

- src/auth_v3.js
The revocation is only handle in the oauthFlow, I think it is to late to catch the error.
Maybe we can remove the fix by @nono on line 287.
> handle revocation in getClient

- src/fetch.js
- test/unit/fetch.js
> [fix] Make sure FetchError has a proper message

- .travis.yml
- CONTRIBUTING.md
- docs/README.md
- docs/oauth.md
- index.html
- test/unit/offline.js
Cf https://github.com/cozy/cozy-stack/pull/435
> Use cozy.tools instead of cozy.local (no need to edit /etc/hosts)

- docs/README.md
Note on promises : promises are in state `rejected` or `fulfilled` according to the documentation : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise, they do not `reject`.
> Some typos

- docs/README.md
- src/files.js
- src/index.js
- test/unit/files.js
> feat: cozy.client.createDirectoryByPath() NOW WITH TESTS 👍🏼

- CHANGELOG.md
- docs/README.md
- src/files.js
- src/mango.js
... and a small fix related to files sorting when offline
> Added wholeResponse param to cozy-data-query

- src/files.js
- src/index.js
Need for https://github.com/cozy/cozy-photos-v3/pull/67
> feat: create a share link from an id

- test/integration/files.js
tests for https://github.com/cozy/cozy-client-js/pull/160
> tests: add test for share links

- src/data.js
When using ACH to import data in a cozy, we would like to import specific IDs in order to import relationship between objects.
To perform such a request, I suggest this code change. What do you think? Do you have another ~~ID~~ idea?
> feat: create data with specific ID

- CHANGELOG.md
- docs/files-api.md
- src/files.js
- src/index.js
- test/integration/files.js
See https://github.com/cozy/cozy-stack/pull/704
> feat: Add a getArchiveLinkByIds method

- docs/intents-api.md
- package.json
- src/intents.js
- test/unit/intents.js
Useful to 'animate' intent resizing using css transitions.
> Add intent transition handling

- docs/intro.md
> Update the install part of the intro

- src/data.js
- test/integration/data.js
- test/unit/data.js
- return directly array of docs
- doesn't include couchDB indexes
> Improve data.findAll()

- CHANGELOG.md
- src/mango.js
- src/utils.js
Following-up on https://github.com/cozy/cozy-client-js/pull/205#issuecomment-327468028
> fix: optimised index creation delay

- CHANGELOG.md
- src/index.js
Adds a `reconnect` flag to the redirection URL so that a special login page is displayed.
> feat: redirect to special reconnect page

- package.json
- yarn.lock
> Add babel polyfill dev peer dependency

- src/files.js
Just an extra option, shouldn't have any effect on existing code.
> feat: add option to create dir by path without pouch

- package.json
- src/index.js
- yarn.lock
> fix: polyfill for object.assign

- docs/auth-api.md
- src/auth_v3.js
Add properties needed by the stack to handle push notification with oauth client. See [cozy-stack doc](https://cozy.github.io/cozy-stack/auth.html#post-authregister) for more infos.
> feat: add notification properties in auth v3

- .babelrc
- package.json
- yarn.lock
Remove custom config to use cozy-app, it fixes the regenerator polyfill issue.
> Use `babel-preset-cozy-app`

- src/intents.js
- test/unit/intents.js
It appears that on some iframe the intent is not maximized (example: Mon Logis).
We may avoid this pain point by maximizing the document dimensions when creating a service.
> ✨  feat: maximize document dimension in intent service

- src/auth_v3.js
See https://github.com/cozy/cozy-stack/issues/1488
> fix: Use the right param for code in OAuth flow

- yarn.lock
See https://github.com/lodash/lodash/pull/4336
> Update dependencies to fix lodash security issue

- src/files.js
We want to allow clients to create and update documents with precise
creation and modification dates (up to the milliseconds).
However, the current way to send those dates, via the `Date` header
does not give us this precision as it is formatted without
milliseconds.
The Cozy stack accepts `CreatedAt` and `UpdatedAt` query-string
parameters to set those attributes during a file or directory creation
and accepts `UpdatedAt` during updates. Those parameters are expected
to follow RFC 3339 (see rfc-editor.org/rfc/rfc3339.txt)
which gives us the opportunity to pass fractions of a second thus
milliseconds.
For retrocompatibility, we leave the option to pass the
`lastModifiedDate` argument to `cozy-client-js` functions but clients
will be able to pass `created_at` and `updated_at` arguments to …
> feat: Send UpdatedAt & CreatedAt with docs
